### ISSUE TITLE
英文译文最后一页有页码

### ISSUE THREAD

**Issue by 1zhistupidboy** [BYRIO/BUPTBachelorThesis#11]
您好，使用中我发现，在英文译文的最后一页中仍然有全局的页码，在nopagenumber范围中都没有页码，只有最后一页有页码。

**Comment by 1zhistupidboy** [comment]
有没有大佬看一看呀

**Comment by Makiras** [comment]
检查一下最新的commit

**Comment by 1zhistupidboy** [comment]
在使用最新的BUPTthesisbachelor.sty后，在外文译文的最后一页仍然有页码
<img width="386" alt="页码" src="https://user-images.githubusercontent.com/101038048/169693440-eae366cf-a779-467b-8c81-6d7c0f84d225.png">

**Comment by 1zhistupidboy** [comment]
谢谢，麻烦您了
