### ISSUE TITLE
GB-7714格式的学位论文引用

### ISSUE THREAD

**Issue by Ailove0106** [BYRIO/BUPTBachelorThesis#13]
您好，我在引用学位论文的时候遇到了以下问题：
按照GB-7714的格式，一个正确的引文应当为：
**李瑞龙. 自动驾驶场景下的三维目标检测技术研究[D]. 辽宁: 中国科学院大学(中国科学院长春光学精密机械与物理研究所), 2022.**
但我使用模版的时候，编译出来的引文格式为：
**辽宁: 中国科学院大学 (中国科学院长春光学精密机械与物理研究所), 2022.**
我看到在'buptbachelor.bst'文件中有对phdthesis/masterthesis类型的引文的格式规定：
```
FUNCTION {phdthesis} {
  start.entry

  format.authors "author"    output.warn
  format.book.title "title"  output.warn
  format.address.school.year output
  format.note                output

  fin.entry
}
```
请问我该如何修改这部分代码，以实现GB-7714格式的引文呢？

**Comment by Makiras** [comment]
能否提供bib文件及相关编译日志？

**Comment by Ailove0106** [comment]
![Snipaste_2022-12-28_11-42-08](https://user-images.githubusercontent.com/47654254/209753737-3cc7a9ea-3eb1-4f45-96f0-aba7ed7ca796.png)
[日志.txt](https://github.com/BYRIO/BUPTBachelorThesis/files/10311969/default.txt)

**Comment by Makiras** [comment]
将 https://github.com/BYRIO/BUPTBachelorThesis/blob/master/buptbachelor.bst#L982  
改为 { "D" }即可
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/22570332/209757519-5cf751dc-1831-4e0a-b4dd-13a2874aefa8.png">
但是我并不确定原作者这么写的用意，最近比较忙，希望有能力的同学可以帮忙。

**Comment by Makiras** [comment]
具体修改请看 https://github.com/BYRIO/BUPTBachelorThesis/commit/d8fc94d98fb60b04c9a96445844cde732dfeabfc

**Comment by Ailove0106** [comment]
收到，我再确认一下教务处的格式要求，万分感谢🙏
祝身体健康，工作顺利
