### ISSUE TITLE
请教如何将该模板与校内overleaf联合使用

### ISSUE THREAD

**Issue by Ziyang1060** [BYRIO/BUPTBachelorThesis#14]
您好，我将项目clone下来之后，打包成zip文件，上传到overleaf网站，但是编译的时候报错。请问是我使用方法不对么？

**Comment by Makiras** [comment]
你好，请提供报错信息的截图，并确认选中了xelatex

**Comment by Ziyang1060** [comment]
你好，之前不知道需要修改编译器为xelatex，使用的是pdflatex，所以报错。修改编译器过后，可成功编译。感谢提醒。
