### ISSUE TITLE
关于正文中的引用

### ISSUE THREAD

**Issue by guanidine** [BYRIO/BUPTBachelorThesis#17]
请问用这个模板的话，可以在正文中引用作者名吗，像有些论文里 "Our approach builds on the “pix2pix” framework of Isola et al." 这样写法？
我使用 `\citeauthor{}` `\citeyear{}`  的时候，输出的 pdf 对应位置是 `author ?` `year ?` ，是因为识别不了模板里的 author 和 year 吗，或者说毕设本来就不能这么引用参考文献？

**Comment by note286** [comment]
我懒得测试了，你参考一下 https://github.com/note286/xduts/discussions/40#discussioncomment-4956807 吧。

**Comment by note286** [comment]
我刚才看了一下源码，BUPTBachelorThesis没有使用`biblatex`，所以估计不太行。

**Comment by guanidine** [comment]
> 我刚才看了一下源码，BUPTBachelorThesis没有使用`biblatex`，所以估计不太行。

感谢您的回复，我试了一下好像确实不行，应该是bst本身就不支持对author-year的引用，谢谢您啦

**Comment by note286** [comment]
是的，`bibtex`不支持，`biblatex`功能更强。
