### ISSUE TITLE
当目录为多页时会出现页眉和页码失效的问题

### ISSUE THREAD

**Issue by kahakaha** [BYRIO/BUPTBachelorThesis#23]
当目录很长，延伸到下一页的时候，页眉和页脚便会失效，我见最新的源码中的pdf也出现了这个问题，请问有什么解决方案吗？

**Comment by kahakaha** [comment]
latex新手一枚，求轻喷。
https://github.com/BYRIO/BUPTBachelorThesis/blob/b7961f19fdff4ffb4947cb46846c7557dec606de/main.tex#L37
我尝试将该行代码中的`\pagestyle{catalogmatter}`改为了`\thispagestyle{catalogmatter}`
第二页的页码显示正常了，页眉也出现了，可是只有第二页的页眉有“北京邮电大学本科毕业设计 (论文)”。
所以，感觉这个bug可能和目录发生了换页有关。

**Comment by Makiras** [comment]
具体原因为  https://github.com/BYRIO/BUPTBachelorThesis/pull/19 这个提交
虽然新定义了fancypagestyle catalogmatter 
![image](https://github.com/BYRIO/BUPTBachelorThesis/assets/22570332/7a873109-2e77-4bf7-9550-a4fdef16983a)
但是忽略了 renewcommand 这一过程
![image](https://github.com/BYRIO/BUPTBachelorThesis/assets/22570332/64ee6b70-01af-4a0f-90f0-540bd4cef47f)

将这个修改回滚，并将catalogmatter 的内容替换进 frontmatter 即可
![image](https://github.com/BYRIO/BUPTBachelorThesis/assets/22570332/e65675c9-1a94-4232-9e6f-eb13278c72e2)

**Comment by kahakaha** [comment]
感谢，我的问题已得到解决，我将关闭这个issue
