### ISSUE TITLE
如何调整参考文献页的缩进

### ISSUE THREAD

**Issue by leeshy-tech** [BYRIO/BUPTBachelorThesis#24]
如果我想要参考文献续行顶格的话要怎么调整呢
![image](https://github.com/BYRIO/BUPTBachelorThesis/assets/56782387/2bea1abd-c563-482a-9d78-01b729a1edf2)

**Comment by note286** [comment]
https://ask.latexstudio.net/ask/question/8178.html

**Comment by leeshy-tech** [comment]
感谢，已解决。
总结：将以下代码加入导言区即可
`\usepackage{xpatch}
\makeatletter
\xapptocmd{\NAT@bibsetnum}{\setlength{\leftmargin}{0pt}\setlength{\itemindent}{\labelwidth}\addtolength{\itemindent}{\labelsep}}{}{}
\makeatother`
![image](https://github.com/BYRIO/BUPTBachelorThesis/assets/56782387/2b917183-2eae-4ae3-80ac-df76d42818ab)
