### ISSUE TITLE
目录中参考文献、致谢等项目没有页码

### ISSUE THREAD

**Issue by AroundKiki** [BYRIO/BUPTBachelorThesis#6]
应该如何修改呢

**Comment by Makiras** [comment]
按照学校2021届的官方要求，这是Feature  
如果仍然需要添加，请参考该 [commit](https://github.com/BYRIO/BUPTBachelorThesis/commit/8eb418d3cb4a78e9f29ee496aea4266b28b977da)

**Comment by AroundKiki** [comment]
请问相关要求哪里能看到细则啊，我看《2021北京邮电大学本科毕业设计（论文）规范》这个文件里面没有提到这个细节，答辩的时候老师不认可无页码

**Comment by Makiras** [comment]
@name1e5s

**Comment by name1e5s** [comment]
[北京邮电大学本科毕业设计模板----毕设模板(参考）.pdf](https://github.com/BYRIO/BUPTBachelorThesis/files/6569001/----.pdf)
如果你们的导员够负责的话在班群的群文件里应该可以找到。

**Comment by name1e5s** [comment]
<img width="647" alt="截屏2021-05-31 下午4 46 03" src="https://user-images.githubusercontent.com/15176913/120166952-bf14e080-c22f-11eb-9d95-815b1a7c5f3f.png">

**Comment by name1e5s** [comment]
若必须保留页码，修改 \begin{nopagenumber} 的位置即可
