### ISSUE TITLE
模板行距问题

### ISSUE THREAD

**Issue by ohhhhhhmygod** [BYRIO/BUPTBachelorThesis#9]
https://github.com/BYRIO/BUPTBachelorThesis/blob/e7a847445af606d8f4c7353fd23ed58795fe8659/BUPTthesisbachelor.sty#L141
这里面把 `baselinestretch` 参数设置为1.3，请问是不是就相当于word里的1.3倍行间距啊，这与论文要求的1.2倍好像不太一样。

**Comment by Makiras** [comment]
参考 [2022 指导文件](https://jwc.bupt.edu.cn/bkbysjlwzdsc.pdf)，确实要求是1.2。但是
word与latex的行距无法直接等价比较
https://liam.page/2013/10/17/LaTeX-Linespace/
https://www.latexstudio.net/archives/10402

**Comment by ohhhhhhmygod** [comment]
收到，感谢社区维护人员:)
